checkpoint_path: /mnt/nw/home/m.yu/repos/foundry/outputs/matryoshka_batch_top_k/block12/2026-04-13_06-11-59/final.pt
activations_path: /mnt/nw/home/m.yu/repos/foundry/tutorials/rfd3_na_tutorial/activations/activations.h5
metadata_dir: /mnt/nw/home/m.yu/repos/foundry/tutorials/rfd3_na_tutorial/activations
hook_name: block12

device: cuda:0
eval_batch_size: 4096

num_features: 12
min_fires: 10
top_residues: 5

out_dir: /mnt/nw/home/m.yu/repos/foundry/outputs/eval/${hook_name}/${now:%Y-%m-%d_%H-%M-%S}                     

hydra:
    run:
      dir: ${out_dir}
    output_subdir: null     # don't nest a .hydra/ folder inside out_dir
    job:                                                                                                                           
      chdir: false
                     