bundle_path: /mnt/nw/home/m.yu/repos/foundry/outputs/classifiers/rf3_safeprotein/fit/rf3_block16_identity
activations_path: /mnt/nw/home/m.yu/repos/foundry/tutorials/sae_data_rf3/uniprot/train_activations/activations/activations.h5
labels_path: /mnt/nw/home/m.yu/repos/foundry/tutorials/classifiers/rf3_safeprotein/labels_test.csv
