bundle_path: outputs/classifiers/rfd3_safeprotein/fit/rfd3_block12_identity__fold4
activations_path: tutorials/sae_data_rfd3_partial/train_activations/activations/activations.h5
labels_path: tutorials/classifiers/rfd3_safeprotein/labels_fold4_test.csv
