positives:
  - /mnt/nw/home/m.yu/repos/foundry/data_pipelines/safeprotein/safeprotein.fasta
negatives:
  - /mnt/nw/home/m.yu/repos/foundry/data_pipelines/uniprot_benigns/benigns.fasta
activations_path: /mnt/nw/home/m.yu/repos/foundry/tutorials/sae_data/train_activations_2/activations/activations.h5
